### ISSUE TITLE
showing edit-popover with accordance to the defined format

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-inputs#12]
Hi Gleb,
When the time format assigned like this `time-format="'HH : mm'"` the popover editor keeps showing the _seconds_ control.
Does it make sense to make the editor showing only the relevant controls? (I mean to hide the _seconds_ control as it is not needed according to the defined `time-format` attribute)

**Comment by g1eb** [comment]
Interesting idea, my opinion on this would be to keep display and functionality separate.
I can imagine a separate option to provide a format for time editing purposes.
