### ISSUE TITLE
"Clear" button text/locale options

### ISSUE THREAD

**Issue by fabiov** [g1eb/angular-datetime-inputs#14]
Add some options to set "Clear" button locale and/or custom text.

**Comment by g1eb** [comment]
Hi Fabio! You can set custom clear text using the `clearText` attribute, for example:

`<date-input date="date" clear-text="Empty"></date-input>`

v0.1.30

**Comment by fabiov** [comment]
Thanks, You've been very helpful !!!

Fabio.

2017-05-09 16:23 GMT+02:00 Gleb <notifications@github.com>:
