### ISSUE TITLE
Anchor trigger? 

### ISSUE THREAD

**Issue by gregory-h** [g1eb/angular-datetime-inputs#15]
Awesome widgets.  Can you provide an example of using an anchor as trigger?

**Comment by g1eb** [comment]
Hi! Do you mean how to open/close datetime inputs on click of a different button? Or using an `<a>` tag as the parent or something?

**Comment by gregory-h** [comment]
Hi


Yes - I'd like to be able to use an anchor to show a datepicker/timepicker/datetimepicker, with the anchor text as the model, or alternatively style the button so it's smaller and displays inline. I tried providing a css-class definition but not sure what the available options are?


Again, awesome components.



Thx,

Greg


________________________________

**Comment by g1eb** [comment]
Ahh, I see. If I understand you correctly you would like to change the styling of the datetime display block that is also used to toggle editing functionality of the inputs, basically like a button. 

You can set the placeholder using the `placeholder` attribute like so:
```<datetime-input placeholder="date input placeholder"></datetime-input>```

and you can bind placeholder to a scope variable too:
```<datetime-input placeholder="{{placeholder}}"></datetime-input>```

Styling is a bit more tricky, but I remember someone did PR for that and you can use the `css-class` attribute to add a custom css class to the datetime display (which is used as a toggle button to open/close datetime edit functionality). To aad a custom css class you would do:
```<datetime-input css-class="my-css-class"></datetime-input>```

and that can be set on the scope as well using:
```<datetime-input css-class="{{myCssClass}}"></datetime-input>```

The tricky part is that you would need to overwrite default styling by adding `.datetime-input.date .display` to your css.

As an example I've put all this info in a little jsfiddle [here](https://jsfiddle.net/e69jbLnj/), let me know if that works for you :)

**Comment by g1eb** [comment]
Hi! Checking in to see if you managed to get this to work yet? Let me know if you need any help :)

**Comment by gregory-h** [comment]
Hi.  Not yet, the use case for it sort of fell off the radar and I haven't revisited since. Thx
________________________________

**Comment by g1eb** [comment]
Alright. I'll close this for now, feel free to reopen when this comes up again :)
