### ISSUE TITLE
Date-format not working...

### ISSUE THREAD

**Issue by franj0** [g1eb/angular-datetime-inputs#17]
Can u help me?
everything looks fine except "date-format" attribute...
In docs stay this
"moment.js compatible date format used for display in date and datetime input directives"

in your example if I change date format into `date-format="DD MMM YYY"`
`<date-input date="now" on-change="print(now)" placeholder="Click Me" date-format='DD MMM YYYY'></date-input>`

it's throwing an error
![image](https://user-images.githubusercontent.com/11553585/29069702-4a97487a-7c3c-11e7-880f-7262589b28d3.png)

if I put dashes between  `DD-MMM-YYYY' there is no error but nothing changed ...
ty

**Comment by g1eb** [comment]
Hi! The format you specify should be a wrapped in quotes to be a string, like this:
```<date-input date="now" on-change="print(now)" placeholder="Click Me" date-format="'DD MMM YYYY'"></date-input>```

**Comment by franj0** [comment]
OMG, tyvm ;)

**Comment by g1eb** [comment]
you're welcome :)
