### ISSUE TITLE
make clear as optional but provide close button like date time range.

### ISSUE THREAD

**Issue by ShankzPatil** [g1eb/angular-datetime-inputs#19]
Make clear button as optional but provide close button like date time range.
so user can close the date picker.

so both range and input looks same in ui.

**Comment by g1eb** [comment]
Good idea, I've added close button to the latest release :)

v0.1.31

**Comment by g1eb** [comment]
And the clear button is now optional

v0.1.32

**Comment by franj0** [comment]
@g1eb can I call clear function from my controller?
Thank you

**Comment by g1eb** [comment]
@franj0 what the clear function does is unset datetime value, or in other words set it to 'undefined'

you can definitely set the value to undefined in your controller, that would achieve the same effect :)
