### ISSUE TITLE
Can create double of time input?

### ISSUE THREAD

**Issue by dotnetDeveloperFumestudtio** [g1eb/angular-datetime-inputs#2]
Hi Markdown 
first thanks for this great inputs
i want to create 3 input in the same page as 
1 - data-time input 
2- time from input
3- time to input 
for create events but i can't do it because the two time input change together 
please advise.

**Comment by g1eb** [comment]
Hi :)

If I understand correctly, you would like to have multiple inputs on the same page bound to different models?

You can totally do that using a different object when you instantiate an input in your html.
The example demo just happens to use the same datetime object.

**Comment by dotnetDeveloperFumestudtio** [comment]
thanks for your respond
yes you understand correctly,but i don't understand  
"You can totally do that using a different object when you instantiate an input in your html."?

**Comment by g1eb** [comment]
Hm, let me see, I think the issue you have is just the way angular works.

Could you share some code where you have an issue? Then I can help and point you in the right direction :)

**Comment by dotnetDeveloperFumestudtio** [comment]
Really i appreciate your Interest
  Event Date:  
`<date-input  date="date" on-change="print(date)" placeholder="Select date"></date-input>`    

  Event Time From:
`<time-input time="time" on-change="print(time)" placeholder="Select time"></time-input>`                 

  Event Time To:
`<time-input time="time" on-change="print(time)" placeholder="Select time"></time-input>` 

i want the two timer input inherit the same date but different time.

**Comment by g1eb** [comment]
Ah, I see! There are two ways to make this work :)

You could instantiate a date object using moment.js, then clone it into two separate objects representing from-time and to-time. Then on change event do some postprocessing or what have you.

Alternatively, we run into a similar requirement on another project and have made a different library for this specific use-case where you need a range input (see https://github.com/g1eb/angular-datetime-range)

**Comment by dotnetDeveloperFumestudtio** [comment]
oooh , thanks a lot 
that is my target , you are amazing 
i appreciate your quick support
