### ISSUE TITLE
timezone

### ISSUE THREAD

**Issue by yoni12ab** [g1eb/angular-datetime-inputs#21]
Hi ,
Great picker !
how can i change time zone in the picker without changing my moment time zone with moment.tz.setDefault ?

**Comment by g1eb** [comment]
Hi there! Thanks, glad you like it :) There is no timezone support (yet)
I've added a utc-offzet attribute to the directive in the [datetime-range](https://github.com/g1eb/angular-datetime-range/issues/14) branch of the range version, but haven't heard anything new about that. Feel free to integrate something like that for this lib.

**Comment by yoni12ab** [comment]
OK thanks I will try
