### ISSUE TITLE
MinuteStep not working

### ISSUE THREAD

**Issue by franj0** [g1eb/angular-datetime-inputs#22]
Hi g1eb,

thank you for your custom directive, it's awesome.

I have issue regarding minuteStep prop, it's seems that does not work at all, nothing happen, no log, no errors, can you help me somehow? Thank you

kind regards

**Comment by g1eb** [comment]
Hi Franjo, thanks! Let me check that for you :)

**Comment by g1eb** [comment]
You're right, it was improperly documented as `minuteStep` and it should be `minute-step`, for example as `minute-step="5"` would increment minute counter with 5 minutes each time.

Let me know if that helps or if you have any other issues :)

**Comment by franj0** [comment]
OMG it is so obvious, it is default syntax for custom directives and
passing props, ty,  I'll try it :)

**Comment by g1eb** [comment]
Yeah, sorry about that! And thanks for spotting an issue in the readme! 😃 

Feel free to close this issue, or let me know if anything else comes up :)

**Comment by g1eb** [comment]
Closing this issue, let me know if anything else comes up :)
