### ISSUE TITLE
How to get the valule using ng-model?

### ISSUE THREAD

**Issue by ynotsarath** [g1eb/angular-datetime-inputs#3]
Not able to get the selected date or time with ng-model

**Comment by g1eb** [comment]
Hi! You can bind date or time value using date="dateobject" (or similarly time="timeobject") instead of using ng-model directive.

Let me know if that works for you.

**Comment by ynotsarath** [comment]
Thanks a lot Gleb!!!!!

It worked for me...

**Comment by g1eb** [comment]
Great, glad it worked out :)
