### ISSUE TITLE
Some ENHANCEMENTS

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-inputs#5]
Hi Gleb,

Thank you for the good tools you are creating!
As you know, I'm interested in `datetime_range` directive you created, and in this `datetime_input` as well :)

I would appreciate if you can consider implementing the below suggestions:
1. When the input has a "Date Mode": close on selection
2. Support for "Scroll over Month" just similarly to what's done for the `range` directive.

Thanks in advance.

**Comment by g1eb** [comment]
Hi :) I'm so glad you like these! And I'm very thankful for your suggestions, let's do this 👍

**Comment by g1eb** [comment]
These input directives are more recent and don't have all extra functionality that _datetime-range_ comes with (yet).

Let me know if you want any other functionality from _datetime-range_ added here, I'd be happy to implement it :)

I've added scroll support for calendar headers in both date and datetime directives.

v0.1.21

**Comment by IbrahimHd** [comment]
that's great Gleb 👍 

It's good if scroll feature becomes available for the `time` directive as well (I didn't mention this coz I thought that it's already available)

**Comment by g1eb** [comment]
Yeah, I agree, added that to the latest version :)

v0.1.22
