### ISSUE TITLE
Bind the directive to ng-model

### ISSUE THREAD

**Issue by IbrahimHd** [g1eb/angular-datetime-inputs#9]
Hi Gleb!
As the directive is built with a `div` element, it becomes not possible to integrate it with `form` **validation** and get the advantages of $dirty, $invalid, .. etc.
Do you agree that converting the directive to `input` element makes it _standardized_ and gives it the power to be used inside `form` element?

thnx in advance.

**Comment by g1eb** [comment]
Good question! Yes and no.

I do agree that it should be an input element for semantic reasons. The reason that it's not an input element yet is because we wanted consistent look and feel for these input directives across all platforms.

On the other hand, if you want the advantage of angular validation you could probably add that without changing the element type. As far as I know [ngModel](https://docs.angularjs.org/api/ng/type/ngModel.NgModelController) directive takes care of that.

**Comment by IbrahimHd** [comment]
Actually I tried using `ngModel` before raising this issue but it **dose not work**.
(I think `$watch` can be used as a workaround solution but it's still not the right approach)
Do you have any insight for solving this issue?

**Comment by g1eb** [comment]
Hmm. Do you still have that snippet by any chance? I can take a look at that and see if I can get the form to work with it :)

PS. If I understand you correctly you want to integrate this directive within a form and have angular validation for $dirty and $invalid states, is that correct? I am a bit confused because rewriting this directive to use input element seems like a different issue.

**Comment by IbrahimHd** [comment]
Hi Gleb,

I've created a simple Plnkr for this purpose: [Find it here](http://plnkr.co/edit/Bnb0ZnMsHCU2aRIlCnpq?p=preview)
You can notice that the form status is not updated (affected) when selecting the date-input directive.
Looking forward you kind feedback.

**Comment by g1eb** [comment]
Thanks! I've added ngModel to the directive in that [plunkr](http://plnkr.co/edit/HmflfRFh2nywoLKKFUUm?p=preview) and form status is updated now.

**Comment by IbrahimHd** [comment]
Great job! 👍 

As `ng-model` is a mandatory attr, is there still a need for specifying the model/object in `date` attr? 
I mean can the directive communicate directly with ngModel and leaving the `date` attr just for specifying the type of the input (with no value injected as it become duplication)?
like this:
`<date-input date ng-model="myRecord.dob" placeholder="Select date" name="dob"></date-input>`

I tested it and it works fine, and even the boundaries (min/max date) functions well, but I need you to confirm if any feature will malfunction when the directive used in that approach.
Thnx

**Comment by g1eb** [comment]
Back in the day, these directives were not built with ngModel in mind.

You are right that supporting ngModel makes custom attributes unnecessary.
Adding support for ngModel is a huge refactor, I would have to rewrite a lot of code.

**Comment by IbrahimHd** [comment]
I've edited my last comment to mention:
> I tested it and it works fine, and even the boundaries (min/max date) functions well, but I need you to confirm if any feature will malfunction when the directive used in that approach.

As the directive is built with/and for AngularJS, it's great and **essential** to support `ngModel`
I do appreciate your effort :-)

**Comment by g1eb** [comment]
I promise I'll think about it, but it's not a quick fix :)

This was not designed to be used with ngModel, and as such it is going to be quite a refactor.
In addition to that, replacing current attributes with ngModel is not backwards compatible.

I might consider making a clone of these directives that are based on ngModel.
For now I think the fastest way for you to use this in an angular form with validation is to fork this repo and add ngModel same way I did in that [plunkr](http://plnkr.co/edit/HmflfRFh2nywoLKKFUUm?p=preview).

**Comment by IbrahimHd** [comment]
Absolutely, the modification you did in plunkr works fine with me, thanks a lot 👍

**Comment by g1eb** [comment]
Allright then, closing this ticket for now.

**Comment by IbrahimHd** [comment]
Hi Gleb,

While I'm taking the code to my dev enviro, I've discovered that the piece of code 
` element.html($sce.getTrustedHtml(ngModel.$viewValue || ''));`
was not working because `$sce` is not injected as a service.
I fixed that, but once `$sce` is injected, the date-input becomes no longer appear!!
[updated plnkr](http://plnkr.co/edit/96iOPmQRFQZxM6w8geni?p=preview)
(it appears if it's commented it out but will stop being associated to `ngModel`)

Appreciated!

**Comment by g1eb** [comment]
Oh yeah, that's because ```$sce``` is used in this case to update element html. That's not necessary as the directive uses custom template for html. Just remove that line and there is no need to inject ```$sce```.

See [updated plunkr](http://plnkr.co/edit/aROVI9TPJ6d86lwr88jJ?p=preview) for reference.

**Comment by IbrahimHd** [comment]
Hi Gleb once again :-)
I have discovered that the form status becomes dirty only when the `date-input` has no initial data and it does not affect when the existing date changed/updated.
I have updated the [plunkr ](http://plnkr.co/edit/GIrm45gEWGA4gDsAhMF3?p=preview)to include 2 `date-input`'s one with no initial date and the other one with initial date.
Could you plz check it and advice accordingly?

**Comment by g1eb** [comment]
Interesting, I'm investigating this, I'll get back to you with a fix :)

If I'm correct, form should be pristine on-load and become dirty when user interacts with it.
(seems like this wasn't happening in the angular demo either)

**Comment by IbrahimHd** [comment]
Hi Gleb,
Eaxactly, the form status is pristine at the initial phase and becomes dirty when something changed.
The issue is that the directive works with ng-model if there is no initial value but does not if there is already a date and has been changed.
Please check the two cases at [this plunker](http://plnkr.co/edit/x3FqR2l3RcvE4uA0rh4D?p=preview)

**Comment by g1eb** [comment]
I think I found the issue, we can trigger ```dirty``` on update of date, even if the field is cleared.
Check this [plunker](http://plnkr.co/edit/HkYudbv6sPdmvFOyo2m5?p=preview).
